### ISSUE TITLE
[1.12.2] NMRC Causes major FPS drop in Avaritia ExtremeCraftingtable

### ISSUE THREAD

**Issue by Morpheus1101** [GotoLink/RecipeHandler#12]
https://github.com/Morpheus1101/Avaritia/issues/78

I have experienced this issue and only occurs when using NMRC

NMRC v0.9
Forge v*.2.2613

**Comment by GotoLink** [comment]
Please try latest version of NoMoreRecipeConflict, and report whether your issue is fixed.

**Comment by Morpheus1101** [comment]
Apologies for the late reply, but this issue still exists as of NMRC v0.10
