### ISSUE TITLE
Pressing the button to cycle through a recipe does not seem to do anything on a server-end

### ISSUE THREAD

**Issue by Sunconure11** [GotoLink/RecipeHandler#14]
Not sure if something happened, but if it helps, I'll share the version of forge I'm on:

1.12.2 - 14.23.2.2619

I seem to be simply unable to cycle through stuff, at least on a server. The issue does not appear in singleplayer.

**Comment by lebanni** [comment]
I have the same issue on only some recipes, mainly bronze tools and sword (Thermal Foundation, Mekanism, Industrial Craft 2, Tech Reborn).

**Comment by GotoLink** [comment]
Usually the craft result refresh doesn't happen on a server the first few times you press it.
Can't explain why but usually the third button press should give the expected behavior.
