### ISSUE TITLE
issues with NoMoreRecipeConflict and armorpus

### ISSUE THREAD

**Issue by IchigoGames** [GotoLink/RecipeHandler#15]
armorplus-1.12.2-11.11.1.37-beta

thedragonlib-1.12.2-5.2.0

MinecraftForge Version:2623

Minecraft 1.12.2

NoMoreRecipeConflict-0.10(1.12.2)

Client or Server?:

[y ] Client
[ y] Server
What happens / happened?: i was using the high tech workbench to craft some lava armor i saw that i could craft items from ImmersiveEngineering and immersivepetroleum as well as vanilla torch from nothing like nothing in the workbench but it lets me pull the item out tested with op and none op players with no change not sure if its this mod or one of the others allowing this to happen.

How can I reproduce it?: add the mods below with armorplus and click on the arrow key to see you can craft things from nothing click the small box with arrow and items pop out.

ImmersiveEngineering-0.12-80-core
immersivepetroleum-1.12.2-1.1.8
NoMoreRecipeConflict-0.10(1.12.2)
https://imgur.com/cCdpMBF

**Comment by Morpheus1101** [comment]
This also occurs with Avaritia Extreme Crafting Table

**Comment by GotoLink** [comment]
The following recipes consider empty crafting space as valid if a subset of a bigger crafting table (9*9 for example):

- immersiveengineering:wooden_devices/reinforced_crate
- immersiveengineering:wooden_devices/item_router
- immersiveengineering:wooden_devices/fluid_router
- immersiveengineering:wirecoils/wirecoil_mv_ins
- immersiveengineering:treated_wood/treated_wood
- immersiveengineering:toolupgrades/drill_lube
- immersiveengineering:stone_decoration/insulating_glass
- immersiveengineering:stone_decoration/concrete2
- immersiveengineering:stone_decoration/concrete
- immersiveengineering:metal_decoration/redstone_engineering
- immersiveengineering:metal_decoration/radiator
- immersiveengineering:material/torch
- immersivepetroleum:tool/projector
- immersivepetroleum:stone_decoration/asphalt2
- immersivepetroleum:stone_decoration/asphalt
- immersivepetroleum:misc/drill_lube_alt

See relevant .json files in assets/'modid'/recipes/ subfolders.
Those are all using a factory as: "ingredient_shaped"="blusunrize.immersiveengineering.common.crafting.RecipeFactoryShapedIngredient"
Which use a derived version of ShapedOreRecipe at:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/crafting/RecipeShapedIngredient.java
The error seems that the recipe is cutoff when trying to fit in bigger space.
Issue has been reported to IE.
https://github.com/BluSunrize/ImmersiveEngineering/issues/3027

**Comment by GotoLink** [comment]
BluSunrize fixed IE issue.
