### ISSUE TITLE
bug with applied energistic and refined storage

### ISSUE THREAD

**Issue by Wireless4024** [GotoLink/RecipeHandler#16]
here is bug from refined storage 
![image](https://user-images.githubusercontent.com/36229606/38169000-cdf4cf1c-3587-11e8-800e-2a54f1200c73.png)

here is bug from applied energistic and wireless crafting terminal
**nothing show**
![image](https://user-images.githubusercontent.com/36229606/38169005-ebcd0a68-3587-11e8-902b-b9df926fba88.png)

**Comment by GotoLink** [comment]
First issue you can change the button position in the configuration file:recipehandler.cfg.
Second issue, it would be easier for AppliedEnergistic to support Forge IRecipeContainer feature, which NoMoreRecipeConflict uses for compatibility handling.
