### ISSUE TITLE
[1.12.2] Conflict with Cyclic & Thaumcraft. *Crashes if viewing Cyclic's 3x3 Crafting Inventory GUI*.

### ISSUE THREAD

**Issue by Z-Tunic** [GotoLink/RecipeHandler#17]
Really unsure if this is even the right place for this...

Minecraft: 1.12.2
Forge: 14.23.3.2673

Mods:
Baubles-1.12-1.5.2
Cyclic-1.12.2-1.14.9
NoMoreRecipeConflict-0.10(1.12.2)
Thaumcraft-1.12.2-6.1.BETA10

-----
Crash Report:
https://pastebin.com/1fiYZUYc

Cyclic adds in a couple items, such as these cakes which when eaten gives you a Extended Inventory Space or a 3x3 Crafting Inventory to use on the go. it seems however if Thaumcraft is installed alongside NoMoreRecipeConflict & Cyclic it causes a crash if viewing Cyclic's 3x3 Crafting Inventory GUI.

Now here's the strange thing with this...

With Cyclic & NoMoreRecipeConflict installed... Cyclic's 3x3 Crafting Inventory works.

With Thaumcraft & NoMoreRecipeConflict installed... I assume it won't crash since... well... no 3x3 Crafting Inventory.

With Cyclic & Thaumcraft installed... Cyclic's 3x3 Crafting Inventory works.

This is quite a strange crash that I can't even figure out. Removing NoMoreRecipeConflict allows Cyclic & Thaumcraft to work fine together but for some bizarre reason it just breaks with NoMoreRecipeConflict installed, yet... if only those two are installed either without NoMoreRecipeConflict or this or that mod with NoMoreRecipeConflict... it works.

**Comment by GotoLink** [comment]
Seems to have been solved on Thaumcraft side:
https://github.com/Azanor/thaumcraft-beta/issues/502
