### ISSUE TITLE
Next Recipe Button in wrong place

### ISSUE THREAD

**Issue by Gazzzaa** [GotoLink/RecipeHandler#19]
After that update the recipe button is now on top of the output slot. It does not look right.

**Comment by GotoLink** [comment]
If you had changes in your configuration file for the button position, you should reset them.

**Comment by gconlon2002** [comment]
There is no configuration folder for this mod

**Comment by Wissi** [comment]
@gconlon2002 there is a configuration file in the /minecraft/config folder. It's called: 

**recipehandler.cfg**

Inside you can "tweak" the recipe button to your needs.

```
    # Offset for button from its default position, negative values to the left, positive to the right [default: 0]
    I:"Cycle Button Horizontal Offset"=0

    # Offset for button from its default position, negative values to under, positive to over [default: 0]
    I:"Cycle Button Vertical Offset"=1```

**Comment by gconlon2002** [comment]
Oh I was looking for the mod name in the configs. Thanks.

**Comment by Wissi** [comment]
Although tweaking the recipe button for a specific mod block will not render correctly for vanilla block anymore. 
In other words in vanilla crafting table it's position is fine and in another modded block it's on top of output. So if you tweak the modded blocks position, it will also be offset in the vanilla crafting table thus making it hard to actually have the button in a certain position for all blocks.
It's the way those blocks are coded I guess.
