### ISSUE TITLE
Button off set if under potion effect

### ISSUE THREAD

**Issue by TOLoneWolf** [GotoLink/RecipeHandler#2]
Mod Version: NoMoreRecipeConflict-0.4(1.9)
minecraft: 1.10.2
forge: 12.18.0.2010
![javaw_2016-07-14_01-09-19](https://cloud.githubusercontent.com/assets/8376628/16829692/b428eff2-495f-11e6-8e5e-1eb56e8c3030.png)
![javaw_2016-07-14_01-10-35](https://cloud.githubusercontent.com/assets/8376628/16829709/d288ba7c-495f-11e6-88eb-0853059bf984.png)

**Comment by EnderT5** [comment]
same bug happens to me

**Comment by GotoLink** [comment]
Doesn't happen with the mod alone.
Might want to check compatibility with the other mods that add icons, like those white-armor-with-dark-square and that chest-with-arrow thingyies.

**Comment by TOLoneWolf** [comment]
Mm sorry about that.
Looks like it does it when JEI(JustEnoughItems) and/or quark(addes the chest looking button) is installed as well.

**Comment by GotoLink** [comment]
I pushed an update for 1.10.2 related to potion effect shift.
Grab latest version on curseforge and report if this issue is fixed please.

**Comment by TOLoneWolf** [comment]
Yep the new version does appear to have fixed the potion shift effect with JEI and quark.
