### ISSUE TITLE
Recipe Button does not display on Tinker's Crafting Station.

### ISSUE THREAD

**Issue by Wissi** [GotoLink/RecipeHandler#20]
You mod is amazing. It is much needed, great work!

Using latest versions of both (as of posting):
NoMoreRecipeConflict-0.11(1.12.2).jar
TConstruct-1.12.2-2.10.1.87.jar

It would display perfectly fine with older versions of both mods, but we updated serve/clients and now it won't display in SP or MP, displays fine in vanilla crafting table, just not in the Tinker's Crafting Station.

**Comment by GotoLink** [comment]
Our latest version changed switch button positionning for improved compatibility.
You may need to refresh config file like issue #19 
I also found another issue relative to TConstruct blocking conflict detection. It has been brought to the attention of TConstruct authors.

**Comment by Wissi** [comment]
Well, I tried that and got mixed results.
I deleted the file:  recipehandler.cfg
Started game, new config file generated. The recipe button now appears in TConstruct crafting station, but it's completely out of place (which can be tweaked with the config - hor/vert offset), but still doesn't work.
So it might now just be as you said: "issue relative to TConstruct blocking conflict detection."?
