### ISSUE TITLE
Not sure whats up, button is greyed out. Cant craft EnderIO gear, Tesla Core overwrites it.

### ISSUE THREAD

**Issue by Slayer5934** [GotoLink/RecipeHandler#23]
Im trying to craft a gear for enderio but tesla core is conflicting with it, strangely enough the switch button just stays greyed out and says 0 conflicts.

Edit1: This also goes for the katana with conflict between dungeontactics and reforged.. This is weird..

Edit2: Heres my mod list https://docs.google.com/spreadsheets/d/e/2PACX-1vTkZG-t1afcKNyPPTd79sOlgnGVQOXTaO1UWjjIIoDbKO0bV9cuLQ1wmEhuDokIxWMJPJbpd8msj6y4/pubhtml

Edit3: I went back to .10 and the switch button works now, sometimes the number of conflicts is still wrong though, and I still cant craft an enderio wooden gear for some reason.

Edit4: This is weird, I went to .11 again and I can still use the switch button on things.. like the katana for example says 3 conflicts, but only 2 are able to be made. For the enderio gear it says 1 conflict but the button is still greyed out.

Edit5: I disabled tesla core lib and I can make the enderio gear now, how come its not detecting a conflict for some items? I also went ahead and reset the recipehandler config and that did nothing.

**Comment by Slayer5934** [comment]
This also goes for the katana with conflict between dungeontactics and reforged.. This is weird..

**Comment by Slayer5934** [comment]
Heres my mod list https://docs.google.com/spreadsheets/d/e/2PACX-1vTkZG-t1afcKNyPPTd79sOlgnGVQOXTaO1UWjjIIoDbKO0bV9cuLQ1wmEhuDokIxWMJPJbpd8msj6y4/pubhtml

**Comment by Slayer5934** [comment]
I went back to .10 and the switch button works now, sometimes the number of conflicts is still wrong though, and I still cant craft an enderio wooden gear for some reason

**Comment by Slayer5934** [comment]
This is weird, I went to .11 again and I can still use the switch button on things.. like the katana for example says 3 conflicts, but only 2 are able to be made. For the enderio gear it says 1 conflict but the button is still greyed out.

**Comment by Slayer5934** [comment]
I disabled tesla core lib and I can make the enderio gear now, how come its not detecting a conflict sometimes?

**Comment by GotoLink** [comment]
Since 1.12; it is possible that some of the mod recipes have conditions and they don't register if some other mods is installed or not.
A new command has been introduced in 0.11 to make it easier to see what happens.

Get the item you want to craft inside your hand then type:
/recipes get by_held
This should report the recipes (name and ingredients) that make the item.
/recipes conflict
This should list the conflicts that can happen globally.
If you find the name of the recipe in the conflict list, note the conflicting recipes names then use each one with:
/recipes get by_name <recipe>

This may help identify the cause of the conflict, and whether it should be solved by NoMoreRecipeConflict.

I notice you have Tinker'sConstruct installed, since there are unsolved issues with the TC crafting station, please make sure to test the vanilla crafting table beforehand.

**Comment by Slayer5934** [comment]
Will do, also, I did test with a vanilla crafting station. Ill report back with the results :) Thanks

**Comment by Slayer5934** [comment]
Okay so for the wooden gear I tested from EnderIO

/recipes get by_held
Result: Nothing shows

/recipes conflict
Result: Nothing shows

/recipes get by_name
Result: Nothing shows

Overall result: Breaks game chat and trying to save and quit results in a hard crash (have to force quit.)

**Comment by Slayer5934** [comment]
Okay so for the crafting table.

/recipes get by_held
Result: Works, shows all recipies.

/recipes conflict
Result: Breaks game, quitting game results in crash.

Overall result: Breaks game chat and trying to save and quit results in a hard crash (have to force quit.)

**Comment by Slayer5934** [comment]
After waiting a LONGGG time, it seems /recipes conflict does actually work, but the sheer amount of mods made for a slow output, ill retry the commands and wait a long time. Edit with results.

**Comment by GotoLink** [comment]
It occurs to me that you could be reading the result wrong. The number on the switch button is the number of possible results for a recipe. If you read "1", there is no conflict.

Though, the first conflict i found for wooden gear in EnderIO, is with AppliedEnergistics2:material, where its damage value is 40, which comes in recipe: grindstone.wooden_gear.

EnderIO itself has 4 recipes for wooden gear, the one with sticks in 4 corners isn't in a conflict with AE2.

**Comment by Slayer5934** [comment]
You can close this issue, I found that Tesla Core Lib was conflicting with EnderIO and that's why I couldn't craft wooden gears from EnderIO. Basically somehow Tesla Core completely overwrites the EnderIO gears.
Basically all I did to fix it is (config > teslacorelib.cfg > B:registerGears=false) and the issue was resolved.
