### ISSUE TITLE
[Suggestion] Disable button for recipes with no conflict

### ISSUE THREAD

**Issue by katubug** [GotoLink/RecipeHandler#28]
Would it be possible to add an option to only display the crafting GUI button when there's more than one output for a recipe?

Thank you for your time!

**Comment by GotoLink** [comment]
The option is available in the configuration file called recipehandler.cfg

**Comment by katubug** [comment]
Ah! My apologies, I was looking for a config file named
"nomorerecipeconflict" so I missed it. Thank you very much for correcting
me!
