### ISSUE TITLE
Don't work with mod Deconstruction Table

### ISSUE THREAD

**Issue by dimitriy0810** [GotoLink/RecipeHandler#3]
In modpack I have mod Deconstruction Table (https://minecraft.curseforge.com/projects/deconstruction-table) and mod NoMoreRecipeConflict. When I try use gunpowder, which have four recipes, in deconstruction table I see one recipe of the four recipes and can't select any other recipe. Also in modpack installed mod industrialcraft 2, which maybe add yet another recipes of gunpowder. Version: 1.7.10. Without ic2 all is work. (Sorry for my English)

**Comment by GotoLink** [comment]
The Deconstruction Table mod handles its own "deconstruction recipes".
There is no way for NoMoreRecipeConflict to predict or react instead of the Deconstruction mod itself.
You should ask on their side for the behavior you'd like to happen.
