### ISSUE TITLE
[1.10.2]Crash when shift clicking in steve's factory manager.

### ISSUE THREAD

**Issue by The-Key** [GotoLink/RecipeHandler#5]
With the latest recommended forge, steve's factory manager and no more recipe conflicts. Using shift to move commands in the inventory manager interface causes this crash: 
[full log.zip](https://github.com/GotoLink/RecipeHandler/files/659770/full.log.zip)

**Comment by GotoLink** [comment]
There are no slots in that interface ?

**Comment by The-Key** [comment]
There aren't but for some reason using shift to keep commands locked to a grid causes it to crash. It only happens if nomorerecipeconflicts is installed. I tried disabling the button render and automatic crafting table support too. I tested with only these 2 mods installed.

**Comment by The-Key** [comment]
`	at net.minecraft.inventory.Container.func_75139_a(Container.java:113) ~[abd.class:?]
	at assets.recipehandler.CraftingHandler.getResultSlot(CraftingHandler.java:118) ~[CraftingHandler.class:?]
	at assets.recipehandler.ClientEventHandler.keyDown(ClientEventHandler.java:87) ~[ClientEventHandler.class:?]`
