### ISSUE TITLE
Crash when using Key Toggle

### ISSUE THREAD

**Issue by Zeevian** [GotoLink/RecipeHandler#6]
Was having errors with JEI GUI rendering, this had conflicted before but a jei update had fixed it.  Having a rendering issue this time with JEI so swapped to use
"Enable Cycle Button = false"
"Enable Cycle Button = true"
This now just causes a crash when opening the controls, or a world, new or old.

http://pastebin.com/3D6Nd1uG

**Comment by GotoLink** [comment]
Can't reproduce.
Possible that the "options.txt" file got corrupted.
