### ISSUE TITLE
[1.11.2-0.6] Mod's button appears in the creative inventory

### ISSUE THREAD

**Issue by starg09** [GotoLink/RecipeHandler#7]
Not the biggest deal, but it'd probably be nicer not to have it there, since it serves no purpose on that GUI :smile:

![image](https://cloud.githubusercontent.com/assets/1235066/24075951/fa36742a-0c04-11e7-8a30-ab72f96d5584.png)

**Comment by GotoLink** [comment]
Side effect of automatically detecting crafting spaces.
There is a logical crafting space on that screen, the slots are simply rendered outside the limits.

**Comment by starg09** [comment]
So, would it be possible to make an exception in that specific case then?
